/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdmissionRequest {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'motivation' : string,
  'program' : string,
}
export interface Article {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'author' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createArticle' : ActorMethod<[string, string, string], bigint>,
  'deleteAdmissionRequest' : ActorMethod<[bigint], undefined>,
  'deleteArticle' : ActorMethod<[bigint], undefined>,
  'getAllAdmissionRequests' : ActorMethod<[], Array<AdmissionRequest>>,
  'getAllPublishedArticles' : ActorMethod<[], Array<Article>>,
  'getArticleById' : ActorMethod<[bigint], Article>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setArticlePublished' : ActorMethod<[bigint, boolean], undefined>,
  'submitAdmissionRequest' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'updateArticle' : ActorMethod<[bigint, string, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];